Update validate-mat-files-workflow.yml

diff --git a/.github/workflows/validate-mat-files-workflow.yml b/.github/workflows/validate-mat-files-workflow.yml
--- a/.github/workflows/validate-mat-files-workflow.yml
+++ b/.github/workflows/validate-mat-files-workflow.yml
@@ -13,15 +13,15 @@ jobs:
     steps:
     - uses: actions/checkout@v3
     
-      - name: Build project
-        run: dotnet build
+    - name: Build project
+      run: dotnet build
         
-      - name: Check .mat file names
-        run: |
-          shopt -s globstar
-          for file in **/*.mat; do
-            if [[ $file != ${file^^} ]]; then
-              echo "ERROR: File name '$file' should be uppercase."
-              exit 1
-            fi
-          done
+    - name: Check .mat file names
+      run: |
+        shopt -s globstar
+        for file in **/*.mat; do
+          if [[ $file != ${file^^} ]]; then
+            echo "ERROR: File name '$file' should be uppercase."
+            exit 1
+          fi
+        done
